# Generated by Django 4.2.10 on 2024-04-14 05:33

import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('publication_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('publication_title', models.CharField(max_length=100)),
                ('publication_description', models.TextField(unique=True)),
                ('publication_creation_date', models.DateField(default=datetime.date.today)),
                ('publication_tags', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=-1), default=list, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('recipe_title', models.CharField(max_length=100)),
                ('recipe_description', models.TextField()),
                ('recipe_ingredients', models.TextField()),
                ('recipe_creation_date', models.DateField(default=datetime.date.today)),
                ('recipe_tags', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=-1), default=list, size=None)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=200, unique=True)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('active', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('description', models.CharField(max_length=240)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecipeVote',
            fields=[
                ('recipe_vote_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vote_type', models.SmallIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodOverflowApp.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeComment',
            fields=[
                ('recipe_comment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comment_body', models.TextField()),
                ('comment_response', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FoodOverflowApp.recipecomment')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodOverflowApp.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PublicationVote',
            fields=[
                ('publication_vote_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vote_type', models.SmallIntegerField(default=0)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodOverflowApp.publication')),
            ],
        ),
        migrations.CreateModel(
            name='PublicationComment',
            fields=[
                ('publication_comment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('comment_body', models.TextField()),
                ('comment_response', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='FoodOverflowApp.publicationcomment')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodOverflowApp.publication')),
            ],
        ),
        migrations.AddField(
            model_name='publication',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
