# Generated by Django 4.2.10 on 2024-04-29 02:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodOverflowApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('avatar_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('avatar_url', models.TextField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar_id',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='FoodOverflowApp.avatar'),
        ),
    ]
