# Generated by Django 4.2.10 on 2024-03-28 19:12

import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodOverflowApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('publication_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('publication_title', models.CharField(max_length=100)),
                ('publication_description', models.TextField(unique=True)),
                ('publication_creation_date', models.DateField(default=datetime.date.today)),
                ('publication_tags', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=-1), default=[], size=None)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
