# Generated by Django 4.2.10 on 2024-03-28 18:29

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodOverflowApp', '0002_publication'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publication',
            old_name='profile_id',
            new_name='profile',
        ),
        migrations.AddField(
            model_name='publication',
            name='publication_creation_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='publication',
            name='publication_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=datetime.date.today, size=None),
            preserve_default=False,
        ),
    ]
