# Generated by Django 4.2.10 on 2024-03-28 18:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodOverflowApp', '0003_rename_profile_id_publication_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='publication_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), size=None),
        ),
    ]
