# Generated by Django 4.2.10 on 2024-05-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodOverflowApp', '0003_savedpost_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='avatar_url',
            field=models.TextField(default='', unique=True),
        ),
    ]
