# Generated by Django 4.2.10 on 2024-05-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodOverflowApp', '0004_alter_avatar_avatar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='publication_description',
            field=models.TextField(),
        ),
    ]
