# Generated by Django 4.2.10 on 2024-03-28 18:39

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodOverflowApp', '0005_alter_publication_publication_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='publication_tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, default=-1), size=None),
        ),
    ]
