# Generated by Django 4.2.10 on 2024-03-28 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FoodOverflowApp', '0006_alter_publication_publication_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='publication_tags',
        ),
    ]
